version: '3'
services:

     ## Postgres Docker Compose Config
  postgres-event:
    container_name: postgres-event
    image: postgres
    environment:
      POSTGRES_DB: event
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    expose:
      - "5431"
    ports:
      - "5431:5431"
    command: -p 5431
    restart: always
    
  postgres-venue:
    container_name: postgres-venue
    image: postgis/postgis
    environment:
      POSTGRES_DB: venue
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    restart: always
    
  postgres-user:
    container_name: postgres-user
    image: postgres
    environment:
      POSTGRES_DB: user
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5433"
    command: -p 5433
    restart: always
    
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
      
  discovery-server:
    image: jacekg11/discovery-server:latest
    container_name: discovery-server
    pull_policy: always
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - zipkin
      
  api-gateway:
    image: jacekg11/api-gateway:latest
    container_name: api-gateway
    pull_policy: always
    ports:
      - "8000:8000"
    expose:
      - "8000"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY= TRACE
    depends_on:
      - zipkin
      - discovery-server
      
  event-core-service:
    container_name: event-core-service
    image: jacekg11/event-core-service:latest
    pull_policy: always
    ports:
     - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - discovery-server
      - api-gateway

      
  event-service:
    container_name: event-service
    image: jacekg11/event-service:latest
    pull_policy: always
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - postgres-event
      - discovery-server
      - api-gateway
     
  user-service:
    container_name: user-service
    image: jacekg11/user-service:latest
    pull_policy: always
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - postgres-user
      - discovery-server
      - api-gateway
      
  venue-service:
    container_name: venue-service
    image: jacekg11/venue-service:latest
    pull_policy: always
    ports:
     - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - postgres-venue
      - discovery-server
      - api-gateway
     
     
     